= DFRobot MiniQ 2WD Library for Arduino =

This project is the unofficial Arduino library for the DFRobot MiniQ 2WD.

Allows for simpler manipulation of functionality of the DFRobot MiniQ 2WD robot. Provides functions for controlling motors and outputs, reading sensors, and handling communication.

See the [Wiki page](https://github.com/bstadick/dfrobot-miniq-2wd/wiki) or the [full documentation](http://bstadick.bitbucket.org/dfrobot2wd/class_d_f_robot2_w_d.html) for use of the library and robot.

== License ==

DFRobot is a trademark of DFRobot. The author of this library does not claim any
ownership or association with DFRobot or their affiliates.

Copyright (c) Bryan Stadick. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
